### PR TITLE
Quick theme

### PR DESCRIPTION
**Pull request by abulte**
Loosely based on template.data.gouv.fr (same blue, use same fonts, Marianne).

Capture d'écran 2019-10-05 13 53 51

_updated screenshot with new menu logic_

There's also a new sidebar menu logic: each guide now has it's own sidebar. I think it's better because we will have some guides with many chapters and we do not want to clutter the sidebar with other guides. This uses https://vuepress.vuejs.org/theme/default-theme-config.html#multiple-sidebars.

Examples with another guide:

Capture d'écran 2019-10-05 13 44 20

Finally, there's also a `<CurrentGroupTOC>` component designed to quickly show "chapters" from a guide's homepage https://github.com/etalab/guides/pull/2/files#diff-ae2f2bc531f5f7ab4ab1c2640fb513acR9.

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
Sounds perfectly fine for a first shot to me. I'm wondering if you could move this to this repo https://github.com/etalab/vuepress-theme-gouv-fr, create a branch (starting from scratch) and then I'll tag a new major version.

We could then say:
- 0.x for this theme is for VuePress 0.x
- 1.x for this theme is for VuePress 1.x

and finally pull the theme as a dependency here

**Comment by AntoineAugusti** [comment]
This can wait a weekday

**Comment by abulte** [comment]
@AntoineAugusti good idea. I think I'll do it later though, once we've iterated a bit on this repo (it's easier at first I think). Then when we are production-ready here, I'll eject the theme, add it to https://github.com/etalab/vuepress-theme-gouv-fr and require it as a dep.

**Comment by AntoineAugusti** [comment]
When approximately do you plan to merge this? I want to contribute to this repo by adding Markdown linting and also adding another guide, let's say Simon's on algorithms

**Pull request merged**
