### PR TITLE
Increase font size

### LINKED ISSUE #17: Augmenter la taille de la police par défaut
Je trouve que la police par défaut est vraiment peu lisible. Est-ce possible de l'augmenter ?

2019-10-13-161505_1920x1080_scrot

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Will fix #17

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
No idea why Now failed 🤷‍♂

**Comment by abulte** [comment]
(undefined) ./datagouv/images/ajouter_une_organisation.JPG 1:0

**Comment by abulte** [comment]
Unrelated, @mathildehg va fixer sur master.

**Comment by AntoineAugusti** [comment]
Fixed in https://github.com/etalab/guides/commit/7c41674710387a9727ed27dc282705c02f2b896b and rebased master

**Pull request merged**
